### PR TITLE
Migrate sdk files to http://downloads.php.net/~windows/php-sdk

### PR DESCRIPTION
**Pull request by bukka**
This migrates the sdk files with added 8.4 version.

### CODE REVIEW

**Comment by bukka** [comment]
This makes the master php-src build work again. I pushed the branch to php/php-sdk-binary-tools so this is what is being used: added in https://github.com/php/php-src/pull/12085 .

It might be just a temporary things - we need to firsts decide if we are going to keep using windows.php.net or move it to downloads. This is really just to make things work in the meantime so I won't be merging this until we make some decisions on it.

Just a note that the preg_match_all  change will be eventually merged in any case as it makes things more robust because currently it depends on html being on a single line which is not ideal...

**Comment by auroraeosrose** [comment]
Binary compatibility is not quite as nasty as it used to be 

https://learn.microsoft.com/en-us/cpp/porting/binary-compat-2015-2017?view=msvc-170

Sooo 

I just built master (8.4) with vs17 (linked against the vc16 libs) with this and - it all just worked - ran the tests and all

note I had to comment out the phpsdk_deps.php check against mixing crts (line 129)
and apply this PR to get the deps downloaded properly

Note: I didn't do a PGO build or other such fun because of the restrictions on binary compatibility with /GL or /LTCG switches- but it'll do for now if you just want to build PHP and work on extensions using the shiny new compiler

**Comment by bukka** [comment]
@shivammathur actually took over all the Windows build stuff so he is the best position to do that as he has access to downloads.php.net/~windows .

**Comment by bukka** [comment]
I think it would be greate to try vs17 as this has been requested by people and if there are no specific blockers, we should at least try it for 8.4,

**Comment by cmb69** [comment]
> I think it would be greate to try vs17 as this has been requested by people and if there are no specific blockers, we should at least try it for 8.4,

Actually. this is a must since [vs16 extended support ends 2017-04-13](https://learn.microsoft.com/en-us/lifecycle/products/visual-studio-2017) while PHP 8.4 is supposed to be supported for a longer time ([even PHP 8.3 is](https://www.php.net/supported-versions)).

**Comment by shivammathur** [comment]
I have copied the series files for master and PHP 8.4 with vs17.

**Comment by cmb69** [comment]
> I have copied the series files for master, PHP 8.3, and PHP 8.4 with vs17.

Thank you, @shivammathur! Unfortunately, I've overlooked that there also should be a copy of `https://downloads.php.net/~windows/php-sdk/deps/vs16/` (i.e. `https://downloads.php.net/~windows/php-sdk/deps/vs17/`). Could you please do that?

Anyhow, with a couple of tweaks and workarounds I've managed to [build 8.4.0alpha von vs17](https://github.com/cmb69/php-ftw/actions/runs/9782041739). :)

**Comment by shivammathur** [comment]
I have copied the directory.

**Comment by cmb69** [comment]
> I have copied the directory.

Thank you; that works fine now.

And a correction regarding the EOL of Visual Studio: [2019 (aka. vs16) has still extended support until 2029-04-10](https://learn.microsoft.com/en-us/lifecycle/products/visual-studio-2019), so there is no *need* to switch to Visual Studio 2022, but I still think it should be done for PHP 8.4.

**Pull request merged**
