### PR TITLE
add mailpit

### PR DESCRIPTION
**Pull request by SakiTakamachi**
For mailpit, the entire license was included in the exe, so there seems to be no need to attach a separate license file.

### CODE REVIEW

**Comment by SakiTakamachi** [comment]
@bukka 

I created a PR for the version that added mailpit.

**Comment by bukka** [comment]
I don't think there are any other arm binaries so not sure if it makes sense to have a single arm binary for mailpit...

**Comment by SakiTakamachi** [comment]
Right. I'll remove it

**Comment by SakiTakamachi** [comment]
done

**Pull request closed without merging**
