### PR TITLE
Upgrade bundled PHP to 8.3.9

### PR DESCRIPTION
**Pull request by cmb69**
I've downloaded https://windows.php.net/downloads/releases/php-8.3.9-nts-Win32-vs16-x64.zip, and replaced the respective files.

Note that this is untested so far. The bundled PHP is used for several tasks; grep for `PHP_SDK_PHP_CMD` to see them. I think we need to ensure that the bundled PHP code isn't broken by upgrading from 8.0.20 to 8.3.9. Maybe some user will want to help with that testing.

Since the bundled may also be used for some custom stuff, we might break things, but of course we can't test that; and such users can stick with `php-sdk-2.3.0` for the time being, anyway.

### CODE REVIEW

**Comment by nono303** [comment]
Hi @cmb69 
Might be an issue building on Windows 7 (see https://github.com/php/php-src/issues/12762)

**Comment by Jan-E** [comment]
I think it is fair to drop Windows 7 and building PHP 7.1. See https://github.com/php/php-sdk-binary-tools/pull/18#issuecomment-2239292720 as well.

**Comment by nono303** [comment]
As U want. personally not a windows 7 user (since few month :shushing_face:) but as php 8.2 security support is ensured until 31 Dec 2026, might be a good compromise to allow 7 users to continue building...

**Comment by cmb69** [comment]
Oh, I had completely forgotten about that, and it's not documented at https://www.php.net/manual/en/install.windows.requirements.php (I'll update that shortly). So I'm not against upgrading to PHP 8.2 only, but on the other hand, [users are supposed to used tagged versions of the PHP SDK anyway](https://github.com/php/php-sdk-binary-tools?tab=readme-ov-file#releases), and `phpsdk-2.3.0` will still be available. And of course, everybody could just replace the bundled PHP with their own version.

@shivammathur, what do you think about ugrading to PHP 8.2 vs. 8.3.

**Comment by shivammathur** [comment]
@cmb69 
Yes, we can upgrade to 8.3 in the next release.

**Comment by cmb69** [comment]
I've ran the php-sdk-binary-tools with 8.3.9 for quite a while now, and didn't notice any issues. Thus, I'm going to commit.

**Pull request merged**
